// Dati mock realistici per sviluppo UI offline (sezione 14 della spec).
// Le strutture rispecchiano lo schema Supabase della sezione 5; tutte le
// referenze incrociate (sub_campagna_id, rdv_id) puntano a id presenti
// nei rispettivi array in questo stesso file.

// ---------- Verticali ----------
export const verticaliMock = [
  {
    id: 'vert-energia',
    nome: 'ENERGIA',
    attivo: true,
    peso_fonte: 40, peso_campagna: 30, peso_geo: 20, peso_consenso: 10,
    soglia_platinum: 80, soglia_gold: 60, soglia_silver: 40,
    consenso_scadenza_giorni: 365,
  },
  {
    id: 'vert-telefonia',
    nome: 'TELEFONIA',
    attivo: true,
    peso_fonte: 45, peso_campagna: 25, peso_geo: 15, peso_consenso: 15,
    soglia_platinum: 78, soglia_gold: 58, soglia_silver: 38,
    consenso_scadenza_giorni: 180,
  },
]

// ---------- Sub-campagne ----------
export const subCampagneMock = [
  {
    id: 'sub-en-leadads-01',
    created_at: '2026-02-12T09:14:00Z',
    verticale_id: 'vert-energia',
    nome: 'Energia Lead Ads Simple',
    formato: 'LEADADS',
    punteggio_base: 55,
    soglia_alert_ore: 4,
    stato: 'attiva',
    webhook_url: 'https://newapp.test/ingest/sub-en-leadads-01',
    webhook_secret: 'whsec_4f7a91b3e2cd',
    webhook_ultimo_test: '2026-05-27T11:42:00Z',
    webhook_ultimo_esito: true,
    lead_30gg: 128,
    score_medio: 58.4,
    tasso_contatto: 71.2,
    spend_30gg: 665.6,
    campagne_collegate: [
      { piattaforma: 'META',   campaign_id: '120216539840260000', spend: 432.10, lead_generate: 82 },
      { piattaforma: 'TIKTOK', campaign_id: 'tk_1762537201',       spend: 233.50, lead_generate: 46 },
    ],
  },
  {
    id: 'sub-en-chatbot-01',
    created_at: '2025-11-04T15:30:00Z',
    verticale_id: 'vert-energia',
    nome: 'Energia Chatbot Standard',
    formato: 'CHATBOT',
    punteggio_base: 82,
    soglia_alert_ore: 6,
    stato: 'attiva',
    webhook_url: 'https://newapp.test/ingest/sub-en-chatbot-01',
    webhook_secret: 'whsec_b7c2148f9a04',
    webhook_ultimo_test: '2026-05-28T08:05:00Z',
    webhook_ultimo_esito: true,
    lead_30gg: 312,
    score_medio: 76.8,
    tasso_contatto: 84.7,
    spend_30gg: 1497.60,
    campagne_collegate: [
      { piattaforma: 'GOOGLE', campaign_id: '17263948275', spend: 1497.60, lead_generate: 312 },
    ],
  },
  {
    id: 'sub-en-landing-01',
    created_at: '2026-01-08T10:00:00Z',
    verticale_id: 'vert-energia',
    nome: 'Energia Landing Pro',
    formato: 'LANDING',
    punteggio_base: 68,
    soglia_alert_ore: 4,
    stato: 'attiva',
    webhook_url: 'https://newapp.test/ingest/sub-en-landing-01',
    webhook_secret: 'whsec_8e21fa6c0b95',
    webhook_ultimo_test: '2026-05-26T14:20:00Z',
    webhook_ultimo_esito: false,
    lead_30gg: 41,
    score_medio: 64.1,
    tasso_contatto: 62.4,
    spend_30gg: 287.0,
    campagne_collegate: [
      { piattaforma: 'META', campaign_id: '120216540001234567', spend: 287.0, lead_generate: 41 },
    ],
  },
  {
    id: 'sub-tel-leadads-01',
    created_at: '2026-03-21T12:45:00Z',
    verticale_id: 'vert-telefonia',
    nome: 'Telefonia Mobile Lead Ads',
    formato: 'LEADADS',
    punteggio_base: 60,
    soglia_alert_ore: 8,
    stato: 'attiva',
    webhook_url: 'https://newapp.test/ingest/sub-tel-leadads-01',
    webhook_secret: 'whsec_c5fa2b18d9e3',
    webhook_ultimo_test: '2026-05-28T07:30:00Z',
    webhook_ultimo_esito: true,
    lead_30gg: 198,
    score_medio: 61.5,
    tasso_contatto: 68.9,
    spend_30gg: 891.0,
    campagne_collegate: [
      { piattaforma: 'META',   campaign_id: '120216540778890123', spend: 612.40, lead_generate: 134 },
      { piattaforma: 'TIKTOK', campaign_id: 'tk_1773812409',       spend: 278.60, lead_generate: 64 },
    ],
  },
  {
    id: 'sub-tel-ivr-01',
    created_at: '2026-04-02T16:00:00Z',
    verticale_id: 'vert-telefonia',
    nome: 'Telefonia IVR Robocall',
    formato: 'IVR',
    punteggio_base: 48,
    soglia_alert_ore: 12,
    stato: 'in_pausa',
    webhook_url: 'https://newapp.test/ingest/sub-tel-ivr-01',
    webhook_secret: 'whsec_a4d801b27e5f',
    webhook_ultimo_test: '2026-05-10T09:00:00Z',
    webhook_ultimo_esito: true,
    lead_30gg: 76,
    score_medio: 44.2,
    tasso_contatto: 31.5,
    spend_30gg: 152.0,
    campagne_collegate: [],
  },
]

// ---------- RDV ----------
export const rdvMock = [
  {
    id: 'rdv-001',
    created_at: '2025-09-15T10:00:00Z',
    ragione_sociale: 'Energica Servizi SRL',
    piva: '12345678901',
    codice_fiscale: '12345678901',
    sdi: 'M5UXCR1',
    pec: 'amministrazione@pec.energicaservizi.it',
    sede_via: 'Via Roma 12',
    sede_cap: '20121',
    sede_citta: 'Milano',
    telefono: '+390283291234',
    email_amministrativa: 'admin@energicaservizi.it',
    referente_nome: 'Marco Bianchi',
    referente_email: 'm.bianchi@energicaservizi.it',
    referente_telefono: '+393489011223',
    commerciale_id: null,
    tier: 'A',
    stato: 'attiva',
    verticali: ['ENERGIA'],
    sub_campagne_attive: ['sub-en-chatbot-01', 'sub-en-leadads-01'],
    volume_max_giornaliero: 150,
    score_minimo: 60,
    algoritmo_distribuzione: 'priority',
    distribuzione_attiva: true,
    riattivazione_at: null,
    fonti_accettate: ['GOOGLE', 'META'],
    webhook_url: 'https://crm.energicaservizi.it/hooks/newapp',
    webhook_auth_type: 'bearer',
    webhook_auth_token: 'enr_brt_8f3a91d2c0e7',
    metodo_integrazione: 'webhook',
    crm_webhook: {
      url: 'https://crm.energicaservizi.it/hooks/newapp',
      method: 'POST',
      auth_type: 'bearer',
      auth_token: 'enr_brt_8f3a91d2c0e7',
      headers: { 'X-Source': 'newapp' },
      mapping: {
        nome: 'first_name',
        cognome: 'last_name',
        telefono: 'phone',
        email: 'email',
        verticale: 'product',
        fascia: 'quality',
      },
      attivo: true,
      ultimo_invio: '2026-05-28T09:32:11Z',
      ultimo_esito: 200,
      invii_oggi: 87,
      errori_oggi: 0,
    },
    wallet_saldo: 2840.50,
    wallet_budget_allocato: 5000.00,
    wallet_soglia_alert: 500.00,
    note_interne: 'Cliente premium, paga sempre puntuale.',
  },
  {
    id: 'rdv-002',
    created_at: '2025-11-22T14:30:00Z',
    ragione_sociale: 'CallPro Italia SPA',
    piva: '09876543210',
    codice_fiscale: '09876543210',
    sdi: 'KRRH6B9',
    pec: 'cuonline@pec.callproitalia.it',
    sede_via: 'Corso Vittorio Emanuele 87',
    sede_cap: '00186',
    sede_citta: 'Roma',
    telefono: '+390645721100',
    email_amministrativa: 'admin@callproitalia.it',
    referente_nome: 'Giulia Esposito',
    referente_email: 'g.esposito@callproitalia.it',
    referente_telefono: '+393355544980',
    commerciale_id: null,
    tier: 'B',
    stato: 'attiva',
    verticali: ['ENERGIA', 'TELEFONIA'],
    sub_campagne_attive: ['sub-tel-leadads-01', 'sub-en-leadads-01'],
    volume_max_giornaliero: 100,
    score_minimo: 50,
    algoritmo_distribuzione: 'proporzionale',
    distribuzione_attiva: true,
    riattivazione_at: null,
    fonti_accettate: ['META', 'TIKTOK', 'AFFILIATO'],
    webhook_url: null,
    webhook_auth_type: 'none',
    webhook_auth_token: null,
    metodo_integrazione: 'portale',
    crm_webhook: null,
    wallet_saldo: 180.00,
    wallet_budget_allocato: 3000.00,
    wallet_soglia_alert: 200.00,
    note_interne: 'Credito quasi esaurito, contattare commerciale.',
  },
  {
    id: 'rdv-003',
    created_at: '2026-02-05T09:15:00Z',
    ragione_sociale: 'Telefonix Servizi SRL',
    piva: '11223344556',
    codice_fiscale: '11223344556',
    sdi: 'USAL8PV',
    pec: 'pec@telefonixsrl.it',
    sede_via: 'Via Garibaldi 45',
    sede_cap: '80142',
    sede_citta: 'Napoli',
    telefono: '+390815512233',
    email_amministrativa: 'amministrazione@telefonixsrl.it',
    referente_nome: 'Paolo Russo',
    referente_email: 'p.russo@telefonixsrl.it',
    referente_telefono: '+393472233445',
    commerciale_id: null,
    tier: 'C',
    stato: 'in_prova',
    verticali: ['TELEFONIA'],
    sub_campagne_attive: ['sub-tel-leadads-01'],
    volume_max_giornaliero: 50,
    score_minimo: 40,
    algoritmo_distribuzione: 'proporzionale',
    distribuzione_attiva: true,
    riattivazione_at: null,
    fonti_accettate: ['META'],
    webhook_url: null,
    webhook_auth_type: 'none',
    webhook_auth_token: null,
    metodo_integrazione: 'email',
    crm_webhook: null,
    wallet_saldo: 600.00,
    wallet_budget_allocato: 800.00,
    wallet_soglia_alert: 150.00,
    note_interne: 'Nuovo cliente in prova, monitorare conversione 30gg.',
  },
  {
    id: 'rdv-004',
    created_at: '2024-12-10T11:20:00Z',
    ragione_sociale: 'Wattline Energia SRL',
    piva: '55667788990',
    codice_fiscale: '55667788990',
    sdi: 'A4707H7',
    pec: 'wattline@pec.wattline.it',
    sede_via: 'Viale del Lavoro 22',
    sede_cap: '37135',
    sede_citta: 'Verona',
    telefono: '+390458001122',
    email_amministrativa: 'admin@wattline.it',
    referente_nome: 'Sara Conti',
    referente_email: 's.conti@wattline.it',
    referente_telefono: '+393391122334',
    commerciale_id: null,
    tier: 'A',
    stato: 'sospesa',
    verticali: ['ENERGIA'],
    sub_campagne_attive: [],
    volume_max_giornaliero: 200,
    score_minimo: 70,
    algoritmo_distribuzione: 'esclusivo',
    distribuzione_attiva: false,
    riattivazione_at: '2026-06-15T00:00:00Z',
    fonti_accettate: ['GOOGLE'],
    webhook_url: 'https://api.wattline.it/v2/leads',
    webhook_auth_type: 'hmac',
    webhook_auth_token: 'wtln_hmac_8c4d12fe',
    metodo_integrazione: 'webhook',
    crm_webhook: {
      url: 'https://api.wattline.it/v2/leads',
      method: 'POST',
      auth_type: 'hmac',
      auth_token: 'wtln_hmac_8c4d12fe',
      headers: {},
      mapping: {
        nome: 'name',
        cognome: 'surname',
        telefono: 'mobile',
        email: 'email',
        verticale: 'category',
        fascia: 'tier',
      },
      attivo: false,
      ultimo_invio: '2026-05-20T18:00:00Z',
      ultimo_esito: 200,
      invii_oggi: 0,
      errori_oggi: 0,
    },
    wallet_saldo: 0.00,
    wallet_budget_allocato: 0.00,
    wallet_soglia_alert: 500.00,
    note_interne: 'Sospesa per mancato saldo. Riattivazione prevista 15/06.',
  },
]

// ---------- Lead ----------
// Helper: costruisce un campaign_name_raw nel formato definito in 10.1
function buildCampaignName({
  id, child, settore, cliente, campagna, offerta, creativita, formato, fonte, versione, automazione,
}) {
  const idFull = child ? `${id}.${child}` : id
  return [idFull, settore, cliente, campagna, offerta, creativita, formato, fonte, versione, automazione]
    .map(v => v ?? '-')
    .join(' | ')
}

export const leadsMock = [
  {
    id: 'lead-0001',
    created_at: '2026-05-28T08:14:33Z',
    nome: 'Luca',
    cognome: 'Ferrari',
    telefono: '+393485671234',
    email: 'luca.ferrari@email.it',
    cap: '20121',
    consent_given: true,
    consent_date: '2026-05-28T08:14:30Z',
    consent_proof: 'trustedform_cert_a8f29d301',
    consent_source: 'TRUSTEDFORM',
    consent_version: 'v3.2',
    consent_scope: ['marketing', 'profilazione'],
    consent_expires_at: '2027-05-28T08:14:30Z',
    consent_revoked_at: null,
    gdpr_audit_log: [{ at: '2026-05-28T08:14:30Z', azione: 'consent_given', source: 'TRUSTEDFORM' }],
    campaign_name_raw: buildCampaignName({
      id: 'CMP001', child: 'V01', settore: 'ENERGIA', cliente: 'EnergiaPro',
      campagna: 'PromoMaggio', offerta: 'LuceGas10', creativita: 'cr_blu_01',
      formato: 'CHATBOT', fonte: 'GOOGLE', versione: 'v2', automazione: 'ELEFANTE',
    }),
    campaign_id: 'CMP001',
    campaign_child_id: 'V01',
    settore: 'ENERGIA',
    cliente: 'EnergiaPro',
    campagna_cliente: 'PromoMaggio',
    offerta: 'LuceGas10',
    creativita: 'cr_blu_01',
    formato: 'CHATBOT',
    fonte: 'GOOGLE',
    versione: 'v2',
    automazione: 'ELEFANTE',
    sub_campagna_id: 'sub-en-chatbot-01',
    parsing_ok: true,
    score: 87,
    score_breakdown: { fonte: 90, campagna: 82, geo: 85, consenso: 90 },
    fascia: 'PLATINUM',
    stato: 'CONSEGNATA',
    rdv_id: 'rdv-001',
    rdv_secondaria_id: null,
    consegnata_at: '2026-05-28T08:14:55Z',
    riciclo_count: 0,
    lista_fredda: false,
    lista_fredda_at: null,
  },
  {
    id: 'lead-0002',
    created_at: '2026-05-28T08:42:01Z',
    nome: 'Anna',
    cognome: 'Greco',
    telefono: '+393331456789',
    email: 'anna.greco@email.it',
    cap: '00186',
    consent_given: true,
    consent_date: '2026-05-28T08:42:00Z',
    consent_proof: 'form_meta_lead_id_8421936',
    consent_source: 'FORM_NATIVO',
    consent_version: 'v3.0',
    consent_scope: ['marketing'],
    consent_expires_at: '2027-05-28T08:42:00Z',
    consent_revoked_at: null,
    gdpr_audit_log: [{ at: '2026-05-28T08:42:00Z', azione: 'consent_given', source: 'FORM_NATIVO' }],
    campaign_name_raw: buildCampaignName({
      id: 'CMP018', child: 'V03', settore: 'ENERGIA', cliente: 'EnergiaPro',
      campagna: 'LeadAdsBase', offerta: 'LuceGas10', creativita: 'cr_video_02',
      formato: 'LEADADS', fonte: 'META', versione: 'v1', automazione: 'GIRAFFA',
    }),
    campaign_id: 'CMP018',
    campaign_child_id: 'V03',
    settore: 'ENERGIA',
    cliente: 'EnergiaPro',
    campagna_cliente: 'LeadAdsBase',
    offerta: 'LuceGas10',
    creativita: 'cr_video_02',
    formato: 'LEADADS',
    fonte: 'META',
    versione: 'v1',
    automazione: 'GIRAFFA',
    sub_campagna_id: 'sub-en-leadads-01',
    parsing_ok: true,
    score: 62,
    score_breakdown: { fonte: 63, campagna: 55, geo: 70, consenso: 70 },
    fascia: 'GOLD',
    stato: 'ASSEGNATA',
    rdv_id: 'rdv-002',
    rdv_secondaria_id: null,
    consegnata_at: null,
    riciclo_count: 0,
    lista_fredda: false,
    lista_fredda_at: null,
  },
  {
    id: 'lead-0003',
    created_at: '2026-05-28T09:05:48Z',
    nome: 'Matteo',
    cognome: 'Romano',
    telefono: '+393294567812',
    email: 'matteo.romano@email.it',
    cap: '10121',
    consent_given: true,
    consent_date: '2026-05-28T09:05:45Z',
    consent_proof: 'tiktok_lead_id_99831245',
    consent_source: 'FORM_NATIVO',
    consent_version: 'v3.0',
    consent_scope: ['marketing'],
    consent_expires_at: '2027-05-28T09:05:45Z',
    consent_revoked_at: null,
    gdpr_audit_log: [{ at: '2026-05-28T09:05:45Z', azione: 'consent_given', source: 'FORM_NATIVO' }],
    // Raw incompleto → parsing_ok = false
    campaign_name_raw: 'CMP033 | ENERGIA | EnergiaPro',
    campaign_id: 'CMP033',
    campaign_child_id: null,
    settore: null,
    cliente: null,
    campagna_cliente: null,
    offerta: null,
    creativita: null,
    formato: null,
    fonte: null,
    versione: null,
    automazione: null,
    sub_campagna_id: null,
    parsing_ok: false,
    score: null,
    score_breakdown: null,
    fascia: null,
    stato: 'RICEVUTA',
    rdv_id: null,
    rdv_secondaria_id: null,
    consegnata_at: null,
    riciclo_count: 0,
    lista_fredda: false,
    lista_fredda_at: null,
  },
  {
    id: 'lead-0004',
    created_at: '2026-05-27T16:21:12Z',
    nome: 'Sofia',
    cognome: 'Marini',
    telefono: '+393482010987',
    email: 'sofia.marini@email.it',
    cap: '50121',
    consent_given: true,
    consent_date: '2026-05-27T16:21:10Z',
    consent_proof: 'trustedform_cert_72be140e',
    consent_source: 'TRUSTEDFORM',
    consent_version: 'v3.2',
    consent_scope: ['marketing', 'profilazione'],
    consent_expires_at: '2026-11-27T16:21:10Z',
    consent_revoked_at: null,
    gdpr_audit_log: [{ at: '2026-05-27T16:21:10Z', azione: 'consent_given', source: 'TRUSTEDFORM' }],
    campaign_name_raw: buildCampaignName({
      id: 'CMP045', child: 'V02', settore: 'TELEFONIA', cliente: 'MobileMax',
      campagna: 'EstateMobile', offerta: 'Mobile5G', creativita: 'cr_estate_01',
      formato: 'LEADADS', fonte: 'META', versione: 'v1', automazione: 'TIGRE',
    }),
    campaign_id: 'CMP045',
    campaign_child_id: 'V02',
    settore: 'TELEFONIA',
    cliente: 'MobileMax',
    campagna_cliente: 'EstateMobile',
    offerta: 'Mobile5G',
    creativita: 'cr_estate_01',
    formato: 'LEADADS',
    fonte: 'META',
    versione: 'v1',
    automazione: 'TIGRE',
    sub_campagna_id: 'sub-tel-leadads-01',
    parsing_ok: true,
    score: 71,
    score_breakdown: { fonte: 75, campagna: 65, geo: 70, consenso: 90 },
    fascia: 'GOLD',
    stato: 'CONSEGNATA',
    rdv_id: 'rdv-002',
    rdv_secondaria_id: 'rdv-003',
    consegnata_at: '2026-05-27T16:21:40Z',
    riciclo_count: 1,
    lista_fredda: false,
    lista_fredda_at: null,
  },
  {
    id: 'lead-0005',
    created_at: '2026-05-26T11:33:22Z',
    nome: 'Davide',
    cognome: 'Bruno',
    telefono: '+393405678123',
    email: null,
    cap: '70121',
    consent_given: true,
    consent_date: '2026-05-26T11:33:20Z',
    consent_proof: 'ivr_call_id_8842311',
    consent_source: 'IMPORT',
    consent_version: 'v2.5',
    consent_scope: ['marketing'],
    consent_expires_at: '2026-08-26T11:33:20Z',
    consent_revoked_at: null,
    gdpr_audit_log: [{ at: '2026-05-26T11:33:20Z', azione: 'consent_given', source: 'IMPORT' }],
    campaign_name_raw: buildCampaignName({
      id: 'CMP051', child: 'V01', settore: 'TELEFONIA', cliente: 'TeleSud',
      campagna: 'IVRPromo', offerta: 'Fisso50', creativita: '-',
      formato: 'IVR', fonte: 'ROBOCALL', versione: 'v1', automazione: 'CONIGLIO',
    }),
    campaign_id: 'CMP051',
    campaign_child_id: 'V01',
    settore: 'TELEFONIA',
    cliente: 'TeleSud',
    campagna_cliente: 'IVRPromo',
    offerta: 'Fisso50',
    creativita: null,
    formato: 'IVR',
    fonte: 'ROBOCALL',
    versione: 'v1',
    automazione: 'CONIGLIO',
    sub_campagna_id: 'sub-tel-ivr-01',
    parsing_ok: true,
    score: 34,
    score_breakdown: { fonte: 45, campagna: 30, geo: 50, consenso: 30 },
    fascia: 'RECYCLE',
    stato: 'IN_RICICLO',
    rdv_id: null,
    rdv_secondaria_id: null,
    consegnata_at: null,
    riciclo_count: 2,
    lista_fredda: false,
    lista_fredda_at: null,
  },
  {
    id: 'lead-0006',
    created_at: '2026-04-12T14:00:00Z',
    nome: 'Elena',
    cognome: 'Costa',
    telefono: '+393389988776',
    email: 'elena.costa@email.it',
    cap: '90121',
    consent_given: true,
    consent_date: '2026-04-12T13:59:55Z',
    consent_proof: 'form_lp_estate_2026',
    consent_source: 'FORM_NATIVO',
    consent_version: 'v3.0',
    consent_scope: ['marketing'],
    consent_expires_at: '2027-04-12T13:59:55Z',
    consent_revoked_at: null,
    gdpr_audit_log: [{ at: '2026-04-12T13:59:55Z', azione: 'consent_given', source: 'FORM_NATIVO' }],
    campaign_name_raw: buildCampaignName({
      id: 'CMP019', child: 'V04', settore: 'ENERGIA', cliente: 'EnergiaPro',
      campagna: 'LandingPro', offerta: 'GasOnly', creativita: 'cr_lp_06',
      formato: 'LANDING', fonte: 'META', versione: 'v2', automazione: 'AQUILA',
    }),
    campaign_id: 'CMP019',
    campaign_child_id: 'V04',
    settore: 'ENERGIA',
    cliente: 'EnergiaPro',
    campagna_cliente: 'LandingPro',
    offerta: 'GasOnly',
    creativita: 'cr_lp_06',
    formato: 'LANDING',
    fonte: 'META',
    versione: 'v2',
    automazione: 'AQUILA',
    sub_campagna_id: 'sub-en-landing-01',
    parsing_ok: true,
    score: 41,
    score_breakdown: { fonte: 55, campagna: 40, geo: 35, consenso: 70 },
    fascia: 'SILVER',
    stato: 'LISTA_FREDDA',
    rdv_id: null,
    rdv_secondaria_id: null,
    consegnata_at: null,
    riciclo_count: 3,
    lista_fredda: true,
    lista_fredda_at: '2026-05-12T10:00:00Z',
  },
  {
    id: 'lead-0007',
    created_at: '2026-05-25T10:12:00Z',
    nome: 'Giorgio',
    cognome: 'Fontana',
    telefono: '+393401239876',
    email: 'giorgio.fontana@email.it',
    cap: '35121',
    consent_given: true,
    consent_date: '2026-05-25T10:11:55Z',
    consent_proof: 'form_meta_lead_id_7720114',
    consent_source: 'FORM_NATIVO',
    consent_version: 'v3.0',
    consent_scope: ['marketing'],
    consent_expires_at: '2027-05-25T10:11:55Z',
    consent_revoked_at: null,
    gdpr_audit_log: [{ at: '2026-05-25T10:11:55Z', azione: 'consent_given', source: 'FORM_NATIVO' }],
    campaign_name_raw: buildCampaignName({
      id: 'CMP018', child: 'V03', settore: 'ENERGIA', cliente: 'EnergiaPro',
      campagna: 'LeadAdsBase', offerta: 'LuceGas10', creativita: 'cr_video_02',
      formato: 'LEADADS', fonte: 'META', versione: 'v1', automazione: 'GIRAFFA',
    }),
    campaign_id: 'CMP018',
    campaign_child_id: 'V03',
    settore: 'ENERGIA',
    cliente: 'EnergiaPro',
    campagna_cliente: 'LeadAdsBase',
    offerta: 'LuceGas10',
    creativita: 'cr_video_02',
    formato: 'LEADADS',
    fonte: 'META',
    versione: 'v1',
    automazione: 'GIRAFFA',
    sub_campagna_id: 'sub-en-leadads-01',
    parsing_ok: true,
    score: 48,
    score_breakdown: { fonte: 55, campagna: 55, geo: 50, consenso: 70 },
    fascia: 'SILVER',
    stato: 'IN_RICICLO',
    rdv_id: null,
    rdv_secondaria_id: null,
    consegnata_at: null,
    riciclo_count: 1,
    lista_fredda: false,
    lista_fredda_at: null,
  },
  {
    id: 'lead-0008',
    created_at: '2026-05-24T17:48:00Z',
    nome: 'Chiara',
    cognome: 'Galli',
    telefono: '+393395567231',
    email: 'chiara.galli@email.it',
    cap: '16121',
    consent_given: true,
    consent_date: '2026-05-24T17:47:50Z',
    consent_proof: 'tiktok_lead_id_55210987',
    consent_source: 'FORM_NATIVO',
    consent_version: 'v3.0',
    consent_scope: ['marketing'],
    consent_expires_at: '2026-06-18T00:00:00Z',
    consent_revoked_at: null,
    gdpr_audit_log: [{ at: '2026-05-24T17:47:50Z', azione: 'consent_given', source: 'FORM_NATIVO' }],
    campaign_name_raw: buildCampaignName({
      id: 'CMP045', child: 'V02', settore: 'TELEFONIA', cliente: 'MobileMax',
      campagna: 'EstateMobile', offerta: 'Mobile5G', creativita: 'cr_estate_01',
      formato: 'LEADADS', fonte: 'TIKTOK', versione: 'v1', automazione: 'TIGRE',
    }),
    campaign_id: 'CMP045',
    campaign_child_id: 'V02',
    settore: 'TELEFONIA',
    cliente: 'MobileMax',
    campagna_cliente: 'EstateMobile',
    offerta: 'Mobile5G',
    creativita: 'cr_estate_01',
    formato: 'LEADADS',
    fonte: 'TIKTOK',
    versione: 'v1',
    automazione: 'TIGRE',
    sub_campagna_id: 'sub-tel-leadads-01',
    parsing_ok: true,
    score: 39,
    score_breakdown: { fonte: 60, campagna: 50, geo: 40, consenso: 70 },
    fascia: 'RECYCLE',
    stato: 'IN_RICICLO',
    rdv_id: null,
    rdv_secondaria_id: null,
    consegnata_at: null,
    riciclo_count: 2,
    lista_fredda: false,
    lista_fredda_at: null,
  },
  // ----- Lead fredde (pool liste fredde, step 12) -----
  {
    id: 'lead-0009',
    created_at: '2026-03-18T09:30:00Z',
    nome: 'Roberto', cognome: 'Sala', telefono: '+393387711002', email: 'roberto.sala@email.it', cap: '24121',
    consent_given: true, consent_date: '2026-03-18T09:29:50Z', consent_proof: 'form_lp_marzo_2026',
    consent_source: 'FORM_NATIVO', consent_version: 'v3.0', consent_scope: ['marketing'],
    consent_expires_at: '2026-05-15T00:00:00Z', consent_revoked_at: null,
    gdpr_audit_log: [{ at: '2026-03-18T09:29:50Z', azione: 'consent_given', source: 'FORM_NATIVO' }],
    campaign_name_raw: buildCampaignName({
      id: 'CMP019', child: 'V04', settore: 'ENERGIA', cliente: 'EnergiaPro', campagna: 'LandingPro',
      offerta: 'GasOnly', creativita: 'cr_lp_06', formato: 'LANDING', fonte: 'META', versione: 'v2', automazione: 'AQUILA',
    }),
    campaign_id: 'CMP019', campaign_child_id: 'V04',
    settore: 'ENERGIA', cliente: 'EnergiaPro', campagna_cliente: 'LandingPro', offerta: 'GasOnly',
    creativita: 'cr_lp_06', formato: 'LANDING', fonte: 'META', versione: 'v2', automazione: 'AQUILA',
    sub_campagna_id: 'sub-en-landing-01', parsing_ok: true,
    score: 45, score_breakdown: { fonte: 55, campagna: 45, geo: 40, consenso: 70 }, fascia: 'SILVER',
    stato: 'LISTA_FREDDA', rdv_id: null, rdv_secondaria_id: null, consegnata_at: null,
    riciclo_count: 3, lista_fredda: true, lista_fredda_at: '2026-04-30T10:00:00Z',
  },
  {
    id: 'lead-0010',
    created_at: '2026-03-22T15:10:00Z',
    nome: 'Francesca', cognome: 'Rizzo', telefono: '+393396622113', email: 'francesca.rizzo@email.it', cap: '40121',
    consent_given: true, consent_date: '2026-03-22T15:09:55Z', consent_proof: 'tiktok_lead_id_33120988',
    consent_source: 'FORM_NATIVO', consent_version: 'v3.0', consent_scope: ['marketing'],
    consent_expires_at: '2027-03-22T15:09:55Z', consent_revoked_at: null,
    gdpr_audit_log: [{ at: '2026-03-22T15:09:55Z', azione: 'consent_given', source: 'FORM_NATIVO' }],
    campaign_name_raw: buildCampaignName({
      id: 'CMP045', child: 'V02', settore: 'TELEFONIA', cliente: 'MobileMax', campagna: 'EstateMobile',
      offerta: 'Mobile5G', creativita: 'cr_estate_01', formato: 'LEADADS', fonte: 'TIKTOK', versione: 'v1', automazione: 'TIGRE',
    }),
    campaign_id: 'CMP045', campaign_child_id: 'V02',
    settore: 'TELEFONIA', cliente: 'MobileMax', campagna_cliente: 'EstateMobile', offerta: 'Mobile5G',
    creativita: 'cr_estate_01', formato: 'LEADADS', fonte: 'TIKTOK', versione: 'v1', automazione: 'TIGRE',
    sub_campagna_id: 'sub-tel-leadads-01', parsing_ok: true,
    score: 38, score_breakdown: { fonte: 60, campagna: 45, geo: 40, consenso: 70 }, fascia: 'RECYCLE',
    stato: 'LISTA_FREDDA', rdv_id: null, rdv_secondaria_id: null, consegnata_at: null,
    riciclo_count: 3, lista_fredda: true, lista_fredda_at: '2026-04-28T10:00:00Z',
  },
  {
    id: 'lead-0011',
    created_at: '2026-02-10T11:00:00Z',
    nome: 'Stefano', cognome: 'Marchetti', telefono: '+393402233447', email: 'stefano.marchetti@email.it', cap: '50122',
    consent_given: true, consent_date: '2026-02-10T10:59:55Z', consent_proof: 'form_lp_feb_2026',
    consent_source: 'FORM_NATIVO', consent_version: 'v3.0', consent_scope: ['marketing'],
    consent_expires_at: '2027-02-10T10:59:55Z', consent_revoked_at: null,
    gdpr_audit_log: [{ at: '2026-02-10T10:59:55Z', azione: 'consent_given', source: 'FORM_NATIVO' }],
    campaign_name_raw: buildCampaignName({
      id: 'CMP019', child: 'V04', settore: 'ENERGIA', cliente: 'EnergiaPro', campagna: 'LandingPro',
      offerta: 'GasOnly', creativita: 'cr_lp_06', formato: 'LANDING', fonte: 'META', versione: 'v2', automazione: 'AQUILA',
    }),
    campaign_id: 'CMP019', campaign_child_id: 'V04',
    settore: 'ENERGIA', cliente: 'EnergiaPro', campagna_cliente: 'LandingPro', offerta: 'GasOnly',
    creativita: 'cr_lp_06', formato: 'LANDING', fonte: 'META', versione: 'v2', automazione: 'AQUILA',
    sub_campagna_id: 'sub-en-landing-01', parsing_ok: true,
    score: 42, score_breakdown: { fonte: 55, campagna: 40, geo: 40, consenso: 70 }, fascia: 'SILVER',
    stato: 'LISTA_FREDDA', rdv_id: null, rdv_secondaria_id: null, consegnata_at: null,
    riciclo_count: 3, lista_fredda: true, lista_fredda_at: '2026-03-15T10:00:00Z',
  },
]

// ---------- Pacchetti freddi (step 12) ----------
// lead_ids: lead incluse nel pacchetto (per i pacchetti attivi guida l'esclusione
// dal pool). n_lead: usato per i pacchetti storici/venduti senza join esplicito.
export const pacchettiFreddiMock = [
  {
    id: 'pkg-001',
    created_at: '2026-05-18T09:00:00Z',
    nome: 'Energia Silver Q1',
    rdv_id: null, // aperto a tutte le RDV
    prezzo_per_lead: 3.5,
    scadenza_at: '2026-07-31T23:59:00Z',
    stato: 'attivo',
    note: 'Pacchetto lead energia fascia silver primo trimestre.',
    lead_ids: ['lead-0011'],
    venduto_at: null,
  },
  {
    id: 'pkg-002',
    created_at: '2026-05-20T14:00:00Z',
    nome: 'Telefonia Recycle Aprile',
    rdv_id: 'rdv-002',
    prezzo_per_lead: 2.8,
    scadenza_at: '2026-06-30T23:59:00Z',
    stato: 'venduto',
    note: 'Venduto a CallPro Italia.',
    lead_ids: [],
    n_lead: 12,
    venduto_at: '2026-06-01T09:00:00Z',
  },
]

// id di tutte le lead già incluse in un pacchetto (attivo o venduto)
export function leadInPacchetto() {
  return new Set(pacchettiFreddiMock.flatMap((p) => p.lead_ids ?? []))
}

// ---------- Serie temporali per Dashboard ----------

// Genera 14 punti giornalieri di volume (ricevute/distribuite) con un trend
// realistico ma deterministico, ancorato a "oggi". Usato dal VolumeChart.
function generaVolume14gg() {
  const punti = []
  const oggi = new Date()
  for (let i = 13; i >= 0; i--) {
    const data = new Date(oggi)
    data.setDate(oggi.getDate() - i)
    // Pattern: weekend ~30% in meno, leggero trend in crescita verso oggi
    const giornoSettimana = data.getDay()
    const fattoreGiorno = giornoSettimana === 0 || giornoSettimana === 6 ? 0.7 : 1
    const fattoreTrend = 1 + (13 - i) * 0.012
    // Componente deterministica pseudo-random basata sul giorno del mese
    const noise = 0.85 + ((data.getDate() * 37) % 30) / 100
    const ricevute = Math.round(310 * fattoreGiorno * fattoreTrend * noise)
    // Tasso distribuzione 70-85%
    const tassoDistr = 0.72 + ((data.getDate() * 53) % 13) / 100
    const distribuite = Math.round(ricevute * tassoDistr)
    punti.push({
      data: data.toISOString().slice(0, 10),
      ricevute,
      distribuite,
    })
  }
  return punti
}

export const volume14ggMock = generaVolume14gg()

// Distribuzione per fonte negli ultimi 30 giorni — usata dal SourceChart.
// Numeri allineati a SPEND e LEAD delle sub-campagne (vedi subCampagneMock)
export const distribuzioneFontiMock = [
  { fonte: 'META',      count: 1420, percentuale: 38.2 },
  { fonte: 'GOOGLE',    count: 980,  percentuale: 26.4 },
  { fonte: 'TIKTOK',    count: 612,  percentuale: 16.5 },
  { fonte: 'AFFILIATO', count: 388,  percentuale: 10.4 },
  { fonte: 'ROBOCALL',  count: 215,  percentuale:  5.8 },
  { fonte: 'IMPORT',    count: 100,  percentuale:  2.7 },
]

// Top sub-campagne attive ordinate per lead 30gg — usata da ActiveSourcesTable
// Restituisce il join sub_campagna + verticale
export function getTopSubCampagne(limit = 5) {
  return subCampagneMock
    .filter((s) => s.stato === 'attiva')
    .slice()
    .sort((a, b) => b.lead_30gg - a.lead_30gg)
    .slice(0, limit)
    .map((s) => {
      const v = verticaliMock.find((x) => x.id === s.verticale_id)
      const cpl = s.lead_30gg > 0 ? s.spend_30gg / s.lead_30gg : 0
      return {
        id: s.id,
        nome: s.nome,
        verticale: v?.nome ?? '—',
        formato: s.formato,
        lead_30gg: s.lead_30gg,
        score_medio: s.score_medio,
        tasso_contatto: s.tasso_contatto,
        cpl,
      }
    })
}

// Activity feed — ultimi 20 eventi (sezione 9.1 della spec).
// Tipi: lead_consegnata, parsing_fallito, lead_riciclata, credito_esaurito, ricarica_wallet
export const activityFeedMock = [
  {
    id: 'act-001',
    at: '2026-05-28T09:32:11Z',
    tipo: 'lead_consegnata',
    descrizione: 'Lead Luca Ferrari consegnata a Energica Servizi SRL',
    link: { tipo: 'lead', id: 'lead-0001' },
  },
  {
    id: 'act-002',
    at: '2026-05-28T09:05:48Z',
    tipo: 'parsing_fallito',
    descrizione: 'Lead CMP033 — campaign_name incompleto, richiede revisione',
    link: { tipo: 'lead', id: 'lead-0003' },
  },
  {
    id: 'act-003',
    at: '2026-05-28T08:42:01Z',
    tipo: 'lead_consegnata',
    descrizione: 'Lead Anna Greco assegnata a CallPro Italia SPA',
    link: { tipo: 'lead', id: 'lead-0002' },
  },
  {
    id: 'act-004',
    at: '2026-05-27T22:14:00Z',
    tipo: 'credito_esaurito',
    descrizione: 'CallPro Italia SPA: credito sotto soglia (€180,00)',
    link: { tipo: 'rdv', id: 'rdv-002' },
  },
  {
    id: 'act-005',
    at: '2026-05-27T18:00:00Z',
    tipo: 'ricarica_wallet',
    descrizione: 'Wattline Energia SRL: wallet azzerato in attesa di saldo',
    link: { tipo: 'rdv', id: 'rdv-004' },
  },
  {
    id: 'act-006',
    at: '2026-05-27T16:21:40Z',
    tipo: 'lead_consegnata',
    descrizione: 'Lead Sofia Marini consegnata a CallPro Italia SPA (secondaria: Telefonix)',
    link: { tipo: 'lead', id: 'lead-0004' },
  },
  {
    id: 'act-007',
    at: '2026-05-26T11:33:22Z',
    tipo: 'lead_riciclata',
    descrizione: 'Lead Davide Bruno in riciclo (2° tentativo)',
    link: { tipo: 'lead', id: 'lead-0005' },
  },
  {
    id: 'act-008',
    at: '2026-05-26T09:12:08Z',
    tipo: 'ricarica_wallet',
    descrizione: 'Energica Servizi SRL: ricarica di €2.000,00 confermata',
    link: { tipo: 'rdv', id: 'rdv-001' },
  },
  {
    id: 'act-009',
    at: '2026-05-25T17:45:33Z',
    tipo: 'lead_consegnata',
    descrizione: 'Lead Telefonia consegnata a Telefonix Servizi SRL',
    link: { tipo: 'rdv', id: 'rdv-003' },
  },
  {
    id: 'act-010',
    at: '2026-05-25T15:22:00Z',
    tipo: 'parsing_fallito',
    descrizione: 'Batch import CMP078 — 4 lead con consenso non valido',
    link: { tipo: 'lead', id: null },
  },
]

// ---------- Movimenti wallet (tab Wallet) ----------
export const walletMovimentiMock = [
  {
    id: 'wm-001',
    created_at: '2026-05-26T09:12:08Z',
    rdv_id: 'rdv-001',
    tipo: 'ricarica',
    descrizione: 'Ricarica bonifico',
    importo: 2000.0,
    saldo_post: 4840.5,
    lead_id: null,
  },
  {
    id: 'wm-002',
    created_at: '2026-05-28T08:14:55Z',
    rdv_id: 'rdv-001',
    tipo: 'lead_ricevuta',
    descrizione: 'Lead PLATINUM Luca Ferrari',
    importo: -12.0,
    saldo_post: 2840.5,
    lead_id: 'lead-0001',
  },
  {
    id: 'wm-003',
    created_at: '2026-05-27T22:14:00Z',
    rdv_id: 'rdv-002',
    tipo: 'lead_ricevuta',
    descrizione: 'Lead GOLD Sofia Marini',
    importo: -8.0,
    saldo_post: 180.0,
    lead_id: 'lead-0004',
  },
  {
    id: 'wm-004',
    created_at: '2026-05-20T11:00:00Z',
    rdv_id: 'rdv-002',
    tipo: 'rettifica',
    descrizione: 'Storno lead duplicata',
    importo: 8.0,
    saldo_post: 188.0,
    lead_id: null,
  },
]

// ---------- Utenti sub-account RDV (tab Utenti) ----------
export const utentiRdvMock = [
  {
    id: 'usr-001',
    rdv_id: 'rdv-001',
    nome: 'Marco Bianchi',
    email: 'm.bianchi@energicaservizi.it',
    ruolo: 'admin',
    ultimo_accesso: '2026-05-31T18:22:00Z',
    stato: 'attivo',
  },
  {
    id: 'usr-002',
    rdv_id: 'rdv-001',
    nome: 'Laura Verdi',
    email: 'l.verdi@energicaservizi.it',
    ruolo: 'operatore',
    ultimo_accesso: '2026-05-30T09:41:00Z',
    stato: 'attivo',
  },
  {
    id: 'usr-003',
    rdv_id: 'rdv-002',
    nome: 'Giulia Esposito',
    email: 'g.esposito@callproitalia.it',
    ruolo: 'admin',
    ultimo_accesso: '2026-05-29T15:10:00Z',
    stato: 'attivo',
  },
  {
    id: 'usr-004',
    rdv_id: 'rdv-002',
    nome: 'Antonio Ferraro',
    email: 'a.ferraro@callproitalia.it',
    ruolo: 'operatore',
    ultimo_accesso: '2026-04-12T11:00:00Z',
    stato: 'sospeso',
  },
]

// Andamento performance 30gg per RDV (tab Performance) — serie deterministica
// di lead consegnate giornaliere, parametrizzata per RDV.
export function generaPerformanceRdv(rdvId, base = 6) {
  const seed = rdvId === 'rdv-001' ? 9 : rdvId === 'rdv-002' ? 5 : 3
  const punti = []
  const oggi = new Date()
  for (let i = 29; i >= 0; i--) {
    const data = new Date(oggi)
    data.setDate(oggi.getDate() - i)
    const gs = data.getDay()
    const fattoreGiorno = gs === 0 || gs === 6 ? 0.6 : 1
    const noise = 0.7 + ((data.getDate() * (seed + 7)) % 30) / 50
    punti.push({
      data: data.toISOString().slice(0, 10),
      consegnate: Math.max(0, Math.round((base + seed) * fattoreGiorno * noise)),
    })
  }
  return punti
}

// ---------- Helpers di lookup ----------
export const findRdvById          = (id) => rdvMock.find(r => r.id === id) ?? null
export const findSubCampagnaById  = (id) => subCampagneMock.find(s => s.id === id) ?? null
export const findVerticaleById    = (id) => verticaliMock.find(v => v.id === id) ?? null
export const findVerticaleByNome  = (nome) => verticaliMock.find(v => v.nome === nome) ?? null
